### ISSUE TITLE
body parameters on path 'auth/refresh'

### ISSUE THREAD

**Issue by Vijay0908** [oscarychen/django-oauth-toolkit-cookie-refresh#1]
Hi, on path 'auth/refresh' what are the body parameters to be passed?

**Comment by oscarychen** [comment]
Hi @Vijay0908, the refresh endpoint requires "client_id" in body. The refresh token is in the header of this request, which will be used to assign a new access token.

The client browser will automatically attach refresh token in the header, because it is set by the log in end point, targeting the path of the refresh endpoint.

**Comment by Vijay0908** [comment]
Hi @oscarychen, it requires 'client id' as a OAuth public client. Now its returning a new access token.Thanks

**Comment by oscarychen** [comment]
> Hi @oscarychen, it requires 'client id' as a OAuth public client. Now its returning a new access token.Thanks

Oh yes, you are right, I forgot about that. I should probably add documentation for the views in README.
